[package]
name = "retro_rust"
version = "0.1.0"
edition = "2024"
license = "MIT"

[build-dependencies]
cc = "1.0"
bindgen = "0.71.1"
cmake = "0.1.54"

[dependencies]
cc = "1.2.25"
flate2 = "1.1.1"
arraydeque = "0.5.1"
image = "0.25"